# Generated by Django 3.2.12 on 2022-12-19 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jee_marks', models.DecimalField(decimal_places=2, max_digits=5, max_length=50)),
                ('hsc_marks', models.DecimalField(decimal_places=2, max_digits=5, max_length=50)),
                ('cet_marks', models.DecimalField(decimal_places=2, max_digits=5, max_length=50)),
                ('diploma_marks', models.DecimalField(decimal_places=2, max_digits=5, max_length=50)),
                ('year_admission', models.IntegerField(default=0)),
                ('category_admission', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_list_num', models.IntegerField()),
                ('is_defaulter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='current_semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=50)),
                ('branch', models.CharField(choices=[('INFT', 'INFT'), ('MECHANICAL', 'MECHANICAL'), ('AI & DS', 'AI & DS'), ('CIVIL', 'CIVIL'), ('CS', 'CS'), ('EXTC', 'EXTC')], default='INFT', max_length=50)),
                ('current_sem', models.CharField(choices=[('SEM 1', 'SEM 1'), ('SEM 2', 'SEM 2'), ('SEM 3', 'SEM 3'), ('SEM 4', 'SEM 4'), ('SEM 5', 'SEM 5'), ('SEM 6', 'SEM 6'), ('SEM 7', 'SEM 7'), ('SEM 8', 'SEM 8')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='family_info_father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('fage', models.IntegerField()),
                ('faddress', models.CharField(max_length=50)),
                ('fcontact_num', models.CharField(max_length=30)),
                ('femail', models.EmailField(default='xyz@gmail.com', max_length=50)),
                ('fqualification', models.CharField(max_length=30)),
                ('foccupation', models.CharField(max_length=30)),
                ('father_image', models.ImageField(upload_to='')),
                ('father_sign', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='family_info_mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=50)),
                ('mage', models.IntegerField()),
                ('maddress', models.CharField(max_length=50)),
                ('mcontact_num', models.CharField(max_length=30)),
                ('memail', models.EmailField(default='xyz@gmail.com', max_length=50)),
                ('mqualification', models.CharField(max_length=30)),
                ('moccupation', models.CharField(max_length=30)),
                ('mother_image', models.ImageField(upload_to='')),
                ('mother_sign', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=30)),
                ('birth_place', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('mother_tongue', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('guardian_name', models.CharField(default='NULL', max_length=30)),
                ('religion', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=30)),
                ('disease', models.CharField(default='None', max_length=30)),
                ('address', models.CharField(default='NULL', max_length=100)),
                ('stud_image', models.ImageField(upload_to='images/')),
                ('stud_sign_image', models.ImageField(upload_to='images/')),
                ('email', models.CharField(default='NULL', max_length=30)),
                ('family_income', models.IntegerField(default=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='semester_sub_ia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_1', models.CharField(max_length=30)),
                ('sub_2', models.CharField(max_length=30)),
                ('sub_3', models.CharField(max_length=30)),
                ('sub_4', models.CharField(max_length=30)),
                ('sub_5', models.CharField(max_length=30)),
                ('sub_6', models.CharField(max_length=30)),
                ('current_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersite.current_semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sibling_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sib_name', models.CharField(default='NULL', max_length=50)),
                ('sib_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50)),
                ('sib_age', models.CharField(max_length=50)),
                ('sib_contact_num', models.CharField(max_length=30)),
                ('sib_qualification', models.CharField(max_length=30)),
                ('sib_occupation', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='admission',
        ),
        migrations.AddField(
            model_name='attendance',
            name='current_sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersite.current_semester'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
