# Generated by Django 3.2.12 on 2022-12-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0002_auto_20221214_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_info',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=50),
        ),
    ]
