# Generated by Django 4.0.1 on 2022-05-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0002_admission_course_admission_midname_admission_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='course',
        ),
    ]
