# Generated by Django 3.2.12 on 2022-12-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0003_personal_details_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='family_income',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='stud_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='stud_sign_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
