# Generated by Django 3.2.12 on 2022-12-14 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersite', '0003_alter_family_info_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='family_info_father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('fage', models.IntegerField()),
                ('faddress', models.CharField(max_length=50)),
                ('fcontact_num', models.CharField(max_length=30)),
                ('femail', models.EmailField(default='xyz@gmail.com', max_length=50)),
                ('fqualification', models.CharField(max_length=30)),
                ('foccupation', models.CharField(max_length=30)),
                ('fparent_image', models.ImageField(upload_to='')),
                ('fparent_sign', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='family_info',
        ),
    ]
