# Generated by Django 4.0.1 on 2022-05-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0003_remove_admission_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='student_image',
            field=models.ImageField(default='no image', upload_to='images'),
            preserve_default=False,
        ),
    ]
