# Generated by Django 4.0.1 on 2022-05-08 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersite', '0005_alter_admission_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='personalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('birthplace', models.CharField(blank=True, max_length=45, null=True)),
                ('mothertongue', models.CharField(blank=True, max_length=45, null=True)),
                ('caste', models.CharField(blank=True, max_length=45, null=True)),
                ('nameofparent', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.CharField(max_length=100)),
                ('mobnumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('emailid', models.EmailField(max_length=254)),
                ('bloodgroup', models.CharField(blank=True, max_length=45, null=True)),
                ('disease', models.CharField(max_length=45)),
                ('fathername', models.CharField(blank=True, max_length=45, null=True)),
                ('mothername', models.CharField(blank=True, max_length=45, null=True)),
                ('fatherage', models.IntegerField()),
                ('motherage', models.IntegerField()),
                ('Faddress', models.CharField(max_length=100)),
                ('Maddress', models.CharField(max_length=100)),
                ('Fnumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Mnumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Fmail', models.EmailField(max_length=254)),
                ('Mmail', models.EmailField(max_length=254)),
                ('Fqualify', models.CharField(blank=True, max_length=45, null=True)),
                ('Mqualify', models.CharField(blank=True, max_length=45, null=True)),
                ('Foccupation', models.CharField(blank=True, max_length=45, null=True)),
                ('Moccupation', models.CharField(blank=True, max_length=45, null=True)),
                ('S1name', models.CharField(blank=True, max_length=45, null=True)),
                ('S2name', models.CharField(blank=True, max_length=45, null=True)),
                ('S3name', models.CharField(blank=True, max_length=45, null=True)),
                ('S1age', models.IntegerField()),
                ('S2age', models.IntegerField()),
                ('S3age', models.IntegerField()),
                ('S1number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('S2number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('S3number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('S1qualify', models.CharField(blank=True, max_length=45, null=True)),
                ('S2qualify', models.CharField(blank=True, max_length=45, null=True)),
                ('S3qualify', models.CharField(blank=True, max_length=45, null=True)),
                ('S1occupation', models.CharField(blank=True, max_length=45, null=True)),
                ('S2occupation', models.CharField(blank=True, max_length=45, null=True)),
                ('S3occupation', models.CharField(blank=True, max_length=45, null=True)),
                ('income', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='admission2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('midname', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
