# Generated by Django 3.2.12 on 2022-12-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0005_family_info_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_semester',
            name='current_sem',
            field=models.CharField(choices=[('SEM 1', 'SEM 1'), ('SEM 2', 'SEM 2'), ('SEM 3', 'SEM 3'), ('SEM 4', 'SEM 4'), ('SEM 5', 'SEM 5'), ('SEM 6', 'SEM 6'), ('SEM 7', 'SEM 7'), ('SEM 8', 'SEM 8')], max_length=50),
        ),
        migrations.AlterField(
            model_name='current_semester',
            name='current_year',
            field=models.CharField(max_length=50),
        ),
    ]
