# Generated by Django 4.0.1 on 2022-05-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0006_personalinfo_admission2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admission2',
        ),
    ]
