# Generated by Django 4.0.1 on 2022-05-08 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersite', '0007_delete_admission2'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1s1', models.IntegerField()),
                ('s1s2', models.IntegerField()),
                ('s1s3', models.IntegerField()),
                ('s1s4', models.IntegerField()),
                ('s1s5', models.IntegerField()),
                ('s1s6', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
