# Generated by Django 3.2.12 on 2022-12-17 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersite', '0007_alter_current_semester_current_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='family_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('contact_num', models.CharField(max_length=30)),
                ('email', models.EmailField(default='xyz@gmail.com', max_length=50)),
                ('qualification', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
                ('parent_image', models.ImageField(upload_to='')),
                ('parent_sign', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='family_info_mother',
            name='user',
        ),
        migrations.AlterField(
            model_name='family_relation',
            name='relation_type',
            field=models.CharField(choices=[('Mother', 'MOTHER'), ('Father', 'FATHER')], max_length=30),
        ),
        migrations.DeleteModel(
            name='family_info_father',
        ),
        migrations.DeleteModel(
            name='family_info_mother',
        ),
        migrations.AddField(
            model_name='family_info',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersite.family_relation'),
        ),
        migrations.AddField(
            model_name='family_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
