# Generated by Django 3.2.12 on 2022-12-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0008_auto_20221217_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_info',
            name='relation',
            field=models.CharField(choices=[('MOTHER', 'MOTHER'), ('MOTHER', 'FATHER')], max_length=30),
        ),
        migrations.DeleteModel(
            name='family_relation',
        ),
    ]
