# Generated by Django 3.2.12 on 2022-12-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0009_auto_20221218_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_semester',
            name='branch',
            field=models.CharField(choices=[('INFT', 'INFT'), ('MECHANICAL', 'MECHANICAL'), ('AI & DS', 'AI & DS'), ('CIVIL', 'CIVIL'), ('CS', 'CS'), ('EXTC', 'EXTC')], default='INFT', max_length=50),
        ),
    ]
