# Generated by Django 4.0.1 on 2022-05-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0010_alter_personalinfo_faddress_alter_personalinfo_fmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='dob',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
