# Generated by Django 4.0.1 on 2022-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0011_alter_personalinfo_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='dob',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='mobnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
