# Generated by Django 4.0.1 on 2022-05-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0012_alter_personalinfo_dob_alter_personalinfo_mobnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='mobnumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
