# Generated by Django 3.2.12 on 2022-12-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0012_auto_20221218_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sibling_details',
            old_name='gender',
            new_name='sib_age',
        ),
        migrations.RenameField(
            model_name='sibling_details',
            old_name='contact_num',
            new_name='sib_contact_num',
        ),
        migrations.RenameField(
            model_name='sibling_details',
            old_name='name',
            new_name='sib_gender',
        ),
        migrations.RenameField(
            model_name='sibling_details',
            old_name='occupation',
            new_name='sib_occupation',
        ),
        migrations.RenameField(
            model_name='sibling_details',
            old_name='qualification',
            new_name='sib_qualification',
        ),
        migrations.RemoveField(
            model_name='sibling_details',
            name='age',
        ),
        migrations.AddField(
            model_name='sibling_details',
            name='sib_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
