# Generated by Django 3.2.12 on 2022-12-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0014_auto_20221209_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_details',
            name='category_admission',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='admission_details',
            name='year_admission',
            field=models.IntegerField(default=2000),
        ),
    ]
