# Generated by Django 3.2.12 on 2022-12-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0014_alter_sibling_details_sib_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sibling_details',
            name='sib_gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50),
        ),
    ]
