# Generated by Django 3.2.12 on 2022-12-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0015_auto_20221210_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_details',
            old_name='ssc_marks',
            new_name='jee_marks',
        ),
    ]
