# Generated by Django 3.2.12 on 2022-12-18 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersite', '0015_alter_sibling_details_sib_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='family_info',
            new_name='family_info_father',
        ),
        migrations.CreateModel(
            name='family_info_mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=50)),
                ('mage', models.IntegerField()),
                ('maddress', models.CharField(max_length=50)),
                ('mcontact_num', models.CharField(max_length=30)),
                ('memail', models.EmailField(default='xyz@gmail.com', max_length=50)),
                ('mqualification', models.CharField(max_length=30)),
                ('moccupation', models.CharField(max_length=30)),
                ('mparent_image', models.ImageField(upload_to='')),
                ('mparent_sign', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
