# Generated by Django 3.2.12 on 2022-12-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0016_auto_20221218_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family_info_father',
            old_name='paddress',
            new_name='faddress',
        ),
        migrations.RenameField(
            model_name='family_info_father',
            old_name='page',
            new_name='fage',
        ),
        migrations.RenameField(
            model_name='family_info_father',
            old_name='parent_image',
            new_name='father_image',
        ),
        migrations.RenameField(
            model_name='family_info_father',
            old_name='parent_sign',
            new_name='father_sign',
        ),
        migrations.RenameField(
            model_name='family_info_father',
            old_name='pcontact_num',
            new_name='fcontact_num',
        ),
        migrations.RenameField(
            model_name='family_info_father',
            old_name='pemail',
            new_name='femail',
        ),
        migrations.RenameField(
            model_name='family_info_father',
            old_name='pname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='family_info_father',
            old_name='poccupation',
            new_name='foccupation',
        ),
        migrations.RenameField(
            model_name='family_info_father',
            old_name='pqualification',
            new_name='fqualification',
        ),
        migrations.RenameField(
            model_name='family_info_mother',
            old_name='mparent_image',
            new_name='mother_image',
        ),
        migrations.RenameField(
            model_name='family_info_mother',
            old_name='mparent_sign',
            new_name='mother_sign',
        ),
        migrations.RemoveField(
            model_name='family_info_father',
            name='prelation',
        ),
    ]
