# Generated by Django 3.2.12 on 2022-12-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0016_rename_ssc_marks_admission_details_jee_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_details',
            name='cet_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
