# Generated by Django 3.2.12 on 2022-12-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0017_admission_details_cet_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission_details',
            name='user',
        ),
    ]
