# Generated by Django 3.2.12 on 2022-12-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0018_semester_sub_ia_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester_sub_ia',
            name='current_semester',
        ),
    ]
