# Generated by Django 3.2.12 on 2022-12-10 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersite', '0018_remove_admission_details_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_details',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
