# Generated by Django 3.2.12 on 2022-12-10 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersite', '0020_auto_20221210_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_details',
            name='category_admission',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='cet_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='year_admission',
            field=models.IntegerField(),
        ),
    ]
