# Generated by Django 3.2.12 on 2022-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0021_auto_20221210_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_details',
            name='cet_marks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='diploma_marks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='hsc_marks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='jee_marks',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='year_admission',
            field=models.CharField(max_length=50),
        ),
    ]
