# Generated by Django 3.2.12 on 2022-12-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0022_auto_20221210_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_details',
            name='cet_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='diploma_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='hsc_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='jee_marks',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission_details',
            name='year_admission',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=50),
        ),
    ]
