# Generated by Django 3.2.12 on 2022-12-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0023_auto_20221211_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_details',
            name='year_admission',
            field=models.IntegerField(),
        ),
    ]
