# Generated by Django 3.2.12 on 2022-12-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0024_alter_admission_details_year_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_details',
            old_name='user',
            new_name='student',
        ),
    ]
