# Generated by Django 3.2.12 on 2022-12-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0025_rename_user_admission_details_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_details',
            old_name='student',
            new_name='user',
        ),
    ]
