# Generated by Django 3.2.12 on 2022-12-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0026_rename_student_admission_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_details',
            name='year_admission',
            field=models.IntegerField(default=0),
        ),
    ]
