# Generated by Django 3.2.12 on 2022-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0028_auto_20221212_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='guardian_name',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
