# Generated by Django 3.2.12 on 2022-12-12 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0030_auto_20221212_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='birth_date',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
    ]
